version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: ["uvicorn", "payroll_inference:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    networks:
      - payroll_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    build: .
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "payroll_ui.py", "--server.address", "0.0.0.0"]
    volumes:
      - .:/app
    networks:
      - payroll_network
    depends_on:
      api:
        condition: service_healthy
    environment:
      - API_URL=http://api:8000

networks:
  payroll_network:
    driver: bridge 